# This workflow will build the SAP Commerce project and runs ant sonarcheck
name: SAP Commerce - SonarQube

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  JDK_VERSION: '11'
  JDK_DISTRIBUTION: 'temurin'
  AWS_S3_BUCKET: ''
  CC_PLATFORM: ''
  CC_INTPK: ''
  CC_CHF: ''

jobs:
  sonar_analysis:
    name: SonarQube Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: ${{ env.JDK_DISTRIBUTION }}

      - name: Import Vault Secrets
        uses: hashicorp/vault-action@v2.4.2
        with:
          url: 
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: |
            secret/explorers_onedce/aws-np accessKeyId | AWS_ACCESS_KEY_ID ;
            secret/explorers_onedce/aws-np secretAccessKey | AWS_SECRET_ACCESS_KEY;
#            secret/explorers_onedce/aws-np aws_region | AWS_REGION

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create directory for Artifacts
        run: mkdir -p downloads/artifacts

      - name: Download the files from S3 to Workspace
        run: aws s3 cp s3://commere-cloud-jenkins/ downloads/artifacts --recursive --no-progress

      - name: Extract Artifacts into hybris/bin
        run: |
          unzip -o -q downloads/artifacts/CXCOMM201100P_21-70005693.ZIP hybris/bin/\* -d core-customize/
          unzip -o -q downloads/artifacts/CXCOMINTPK210200P_4-80005851.ZIP hybris/bin/\* -d core-customize/
          unzip -o -q downloads/artifacts/cloudhotfolders_2011.zip -d core-customize/hybris/bin/modules      

      - name: Set Ant Environment & Build
        run: |
          cd core-customize/hybris/bin/platform
          . ./setantenv.sh
          ant clean all

      - name: Running Ant Sonarcheck
        run: |
          cd core-customize/hybris/bin/platform
          ant sonarcheck